### ISSUE TITLE
PARTUUID and PARTLABEL support

### ISSUE THREAD

**Issue by E5ten** [slashbeast/mdev-like-a-boss#4]
Wouldn't supporting these, which would clear a TODO item, only require adding 2 matching lines after
```bash
		[ "${UUID}" ] && create_uuid_label_symlink 'uuid' "${UUID}"
		[ "${LABEL}" ] && create_uuid_label_symlink 'label' "${LABEL}"
```
That are identical except for adding PART/part in front of the relevant places?

**Comment by slashbeast** [comment]
I think i opted out of that because busybox's blkid does not support that, but looking at the code, since it already unset PARTLABEL and PARTUUID there's no harm in adding it. Will push code for that tomorrow.

**Comment by slashbeast** [comment]
Hi,

I dropped PARTLABEL after realizing it's generic and not unique, nothing good will come from using it.

**Comment by E5ten** [comment]
That makes sense, PARTUUID was all I cared about anyway.

**Comment by slashbeast** [comment]
Out of curiosity, what's your usecase for mdev? I do not think a lot of people uses it apart from embedded.

**Comment by E5ten** [comment]
I wanted to get rid of udev and it's the only alternative I know of. I'm using https://skarnet.org/software/mdevd/index.html instead of busybox mdev.

**Comment by slashbeast** [comment]
I was not aware mdevd was a thing, I need to support it in OpenRC init then. I have on TODO list to integrate busybox's mdev with uevent helper, so it would use the events rather than hotplug agent interface.

**Comment by E5ten** [comment]
For myself, most of the stuff in mdev.init was already in the devfs initscript, and I dealt whatever I needed that wasn't in mdev.conf, so this is the initscript I use for mdevd, I'm pretty sure I took some of it from elsewhere:
```shell
#!/sbin/openrc-run

supervisor='supervise-daemon'
name='Kernel Device Manager'
description='A netlink-listening device manager similar to mdev'

extra_started_commands='reload'
description_reload='Reload the configuration file'

: "${cfgfile:=/etc/mdev.conf}"

required_files="${cfgfile}"

command='/usr/bin/mdevd'
command_args="-f ${cfgfile} ${command_args:-}"

start_post() {
    mdevd-coldplug
}

depend() {
    provide dev
    need sysfs dev-mount
    before checkfs fsck
    keyword -containers -lxc -vserver
}

reload() {
    ebegin "Reloading ${name} configuration"
    supervise-daemon --signal HUP
    eend "$?"
}
```
