### ISSUE TITLE
mdev without xf86-input-keyboard and xf86-input-mouse on gentoo

### ISSUE THREAD

**Issue by insanitywholesale** [slashbeast/mdev-like-a-boss#8]
Since those two drivers were removed from upstream and from the gentoo repos, what is the recommendation for getting input working now if any?

**Comment by insanitywholesale** [comment]
Update: by using a patch from KISS Linux, modifying a couple ebuilds and using static files in `/etc/X11/xorg.conf.d/` I was able to get libinput to install and work.

References:
https://github.com/kisslinux/repo/blob/master/extra/libinput/patches/libinput-optional-udev.patch
https://github.com/insanitywholesale/inherently-overlay/tree/master/dev-libs/libinput
https://github.com/insanitywholesale/inherently-overlay/tree/master/x11-base/xorg-drivers
https://k1ss.org/wiki/dev/replacing-udev

**Comment by rofl0r** [comment]
@insanitywholesale nice work, it might be helpful to add the specific git revision of those repos (at least the kisslinux one) at the current time for future reference

**Comment by insanitywholesale** [comment]
currently at the following commit https://github.com/kisslinux/repo/commit/086a0c131811e2c4ddc5ed8a2fcfcfba65218e6e which is for libinput 1.15.5

**Comment by newincpp** [comment]
I was trying to setup this on my machine but libinput but gentoo has removed version before 1.18 and this kisslinux patch stopped at 1.15. Support has been removed here: https://github.com/kisslinux/repo/commit/1151d1fd05427ceb46da958a7205e985bbf80ce4#diff-12cfe5f7f8f0f3e1dbedf3e7af86867c8d61b5a7d47892434d7e15d0b4591f52 and now require udev again. It looks like a lot of work to adapt it to the latest version (and even more to maintain it) so I'm not sure I want to get into that.
Is there other options available ? If yes I can't find any.

**Comment by slashbeast** [comment]
I am pretty sure x11-drivers/xf86-input-evdev can work with static configuration, but in this time and age I do not think running a desktop system without udev is wise. mdev-like-a-boss was a research project that lasted way too long, I've been doing it for 8 years at the point I decided to drop it.

Now that udev actually can be linked against musl-libc I see absolute no reason to not use udev on a desktop, and if you are going embedded, devtmpfs might be all you need anyway.
